# Generated by Django 3.2.24 on 2024-03-13 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='user_profile',
            new_name='profile_user',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='added_date',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='slug',
        ),
    ]
